# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Item Category'},
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(max_length=30, unique=True, verbose_name='Item tag'),
        ),
    ]
